export const everydayLifeQuestions = [
    "What's the first thing you do when you wake up?",
    "What's the first thing you do when you get home?",
    "What's the most normal thing to do when you're bored?",
    "What's the most common thing people forget?",
    "What's the most normal thing to do before bed?",
    "What's the most common thing people lose?",
    "What's the best thing to do on a free afternoon?",
    "What's the most normal thing to wear around the house?",
    "What's the most common household chore?",
    "What's the most normal thing to do while waiting?",
    "What's the first thing you would grab before leaving home?",
    "What's the most common reason people check their phone?",
    "What's the best thing to do on a rainy day?",
    "What's the most normal way to spend a Sunday?",
    "What's the most common thing people complain about?",
    "What's the best thing to do when you can't sleep?",
    "What's the most normal thing to do after lunch?",
    "What's the most common thing people leave at home?",
    "What's the best way to spend a lazy day?",
    "What's the most normal thing to do while watching TV?",
    "What's the most common thing people carry around?",
    "What's the best thing to do when you're waiting for someone?",
    "What's the most normal thing to do on a Saturday morning?",
    "What's the most common thing people forget when leaving the house?",
    "What's the best thing to do after finishing a long task?",
    "What's the most normal thing to do before going somewhere?",
    "What's the most common thing people keep beside their bed?",
    "What's the best thing to do when you have nothing planned?",
    "What's the most normal thing to do after school or work?",
    "What's the most common thing people clean?",
    "What's the best thing to do on a quiet evening?",
    "What's the most normal thing to do while listening to music?",
    "What's the most common thing people check before leaving?",
    "What's the best thing to do when you get an unexpected free hour?",
    "What's the most normal thing to do on a public holiday?",
    "What's the most common thing people keep in their pockets?",
    "What's the best thing to do when the weather is perfect?",
    "What's the most normal thing to do before a meal?",
    "What's the most common thing people do when they are tired?",
    "What's the best thing to do during a long car trip?",
    "What's the most normal thing to do when you're waiting in a queue?",
    "What's the most common thing people do first on a day off?",
    "What's the best thing to do after dinner?",
    "What's the most normal thing to do when you hear your phone ring?",
    "What's the most common thing people put on a bedside table?",
    "What's the best thing to do when you finish everything early?",
    "What's the most normal thing to do when you're feeling lazy?",
    "What's the most common thing people check before going to bed?",
    "What's the best way to spend an afternoon at home?",
    "What's the most normal thing to do when you suddenly have plans cancelled?"
];
