export const familyQuestions = [
    "What's the most common thing families argue about?",
    "What's the most normal family dinner?",
    "What's the most annoying thing a sibling can do?",
    "What's the most normal thing to do on a family weekend?",
    "What's the most common thing parents remind people about?",
    "What's the best family activity?",
    "What's the most common reason a family is late?",
    "What's the most normal thing to watch together?",
    "What's the most common thing families do on holidays?",
    "What's the best family meal?",
    "What's the most normal thing to do on a family road trip?",
    "What's the most common thing siblings fight over?",
    "What's the best thing about having a family day?",
    "What's the most normal family tradition?",
    "What's the most common thing found in a family kitchen?",
    "What's the most normal thing to do after dinner?",
    "What's the most common thing families forget when going somewhere?",
    "What's the best family game?",
    "What's the most normal thing to do on a family birthday?",
    "What's the most common thing people hear from their parents?",
    "What's the most normal family outing?",
    "What's the best thing to do together on a rainy day?",
    "What's the most common thing families watch on TV?",
    "What's the most normal thing to argue about in the car?",
    "What's the best family holiday activity?",
    "What's the most common thing siblings borrow from each other?",
    "What's the most normal thing to do when guests visit?",
    "What's the most common thing families have for dessert?",
    "What's the best thing about eating dinner together?",
    "What's the most normal thing to do before a family trip?",
    "What's the most common thing parents ask people to clean?",
    "What's the best family tradition?",
    "What's the most normal thing to do on a Sunday with family?",
    "What's the most common thing people leave lying around at home?",
    "What's the best family movie?",
    "What's the most normal thing to bring to a family picnic?",
    "What's the most common thing families do after lunch?",
    "What's the best family board game?",
    "What's the most normal thing to do when a relative visits?",
    "What's the most common thing people complain about at home?",
    "What's the best family breakfast?",
    "What's the most normal thing to do on a family birthday?",
    "What's the most common thing people share with siblings?",
    "What's the best thing to do together after dinner?",
    "What's the most normal family photo?",
    "What's the most common thing families pack for a day out?",
    "What's the best family activity outside?",
    "What's the most normal thing to do during a family celebration?",
    "What's the most common thing families do when the weather is bad?",
    "What's the best thing about a family weekend?"
];
