export const foodQuestions = [
    "What's the most normal breakfast?",
    "What's the most common pizza topping?",
    "What's the best thing to put on toast?",
    "What's the most normal sandwich filling?",
    "What's the most common takeaway order?",
    "What's the best snack for watching a movie?",
    "What's the most normal thing to eat at lunchtime?",
    "What's the most common fruit?",
    "What's the most common vegetable?",
    "What's the most normal thing to put in a lunchbox?",
    "What's the best flavour of ice cream?",
    "What's the most common party food?",
    "What's the most normal thing to eat on a rainy day?",
    "What's the most common drink to have with dinner?",
    "What's the best food for a picnic?",
    "What's the most common thing people put on chips?",
    "What's the most normal food to eat at a barbecue?",
    "What's the most common cereal?",
    "What's the best thing to put in a wrap?",
    "What's the most normal dessert?",
    "What's the most common thing to order at a cafe?",
    "What's the best food to eat while travelling?",
    "What's the most normal food to bring to a friend's house?",
    "What's the most common thing to put in a salad?",
    "What's the best food to eat when you're hungry?",
    "What's the most normal food at a birthday party?",
    "What's the most common flavour of soft drink?",
    "What's the best thing to dip into sauce?",
    "What's the most normal food to eat at a sports game?",
    "What's the most common type of biscuit?",
    "What's the best food to share?",
    "What's the most normal thing to have in the fridge?",
    "What's the most common thing people put in a sandwich?",
    "What's the best food to eat on a road trip?",
    "What's the most normal food to have after school?",
    "What's the most common type of chocolate?",
    "What's the best food to eat at a picnic?",
    "What's the most normal thing to order at a fast-food restaurant?",
    "What's the most common thing people put on pancakes?",
    "What's the best flavour of chips?",
    "What's the most normal thing to eat before going somewhere?",
    "What's the most common food at a family dinner?",
    "What's the best thing to put on a burger?",
    "What's the most normal thing to eat while watching TV?",
    "What's the most common thing people forget when packing lunch?",
    "What's the best food to have at a party?",
    "What's the most normal thing to eat on a cold day?",
    "What's the most common food people eat when they're celebrating?",
    "What's the best food to eat when you don't know what you want?",
    "What's the most normal food to order when eating out?"
];
