export const moneyQuestions = [
    "What's the first thing you'd buy with $20?",
    "What's the first thing you'd buy with $100?",
    "What's something people commonly save money for?",
    "What's the most normal thing to spend $10 on?",
    "What's the most common impulse purchase?",
    "What's something people often forget costs money?",
    "What's the best thing to save money for?",
    "What's the most normal thing to buy at a supermarket?",
    "What's something people commonly buy when they're bored?",
    "What's the most normal thing to spend pocket money on?",
    "What's something that's surprisingly expensive?",
    "What's the most common thing people buy as a gift?",
    "What's the best thing to spend birthday money on?",
    "What's the most normal thing to buy at a shopping centre?",
    "What's something people often buy more than they need?",
    "What's the most common thing people save up for?",
    "What's the best thing to get for free?",
    "What's the most normal reason to check your bank balance?",
    "What's something people commonly buy online?",
    "What's the most normal thing to spend spare change on?",
    "What's something people often regret buying?",
    "What's the best thing to spend a gift card on?",
    "What's the most common thing people buy at a convenience store?",
    "What's the most normal thing to buy before a trip?",
    "What's something people commonly share to save money?",
    "What's the best thing to spend $5 on?",
    "What's the most normal thing to buy at a market?",
    "What's something people often forget to budget for?",
    "What's the most common thing people buy when they're hungry?",
    "What's the best thing to save for a rainy day?",
    "What's the most normal thing to buy for your room?",
    "What's something people commonly spend too much money on?",
    "What's the most normal thing to buy at a petrol station?",
    "What's the best thing to buy with your first pay?",
    "What's something people commonly borrow instead of buying?",
    "What's the most normal thing to buy for a party?",
    "What's something people usually compare prices on?",
    "What's the best thing to buy when you have a discount?",
    "What's the most common thing people buy at a cafe?",
    "What's something people commonly keep receipts for?",
    "What's the most normal thing to spend money on during a day out?",
    "What's the best thing to get as a present?",
    "What's something people commonly save coins for?",
    "What's the most normal thing to buy on holiday?",
    "What's something people often spend money on without planning?",
    "What's the best bargain you've ever found?",
    "What's the most common thing people buy for their home?",
    "What's the most normal thing to buy when moving somewhere new?",
    "What's something everyone seems to think is too expensive?",
    "What's the most sensible thing to save money for?"
];
