export const otherQuestions = [
    "What's the most normal thing to do on a Saturday?",
    "What's the most common thing people do when they're bored?",
    "What's the most normal thing to have in your room?",
    "What's the most common thing people do when they get a new phone?",
    "What's the best thing to do with an unexpected free hour?",
    "What's the most normal thing to do when it starts raining?",
    "What's the most common thing people take photos of?",
    "What's the most normal thing to do when meeting someone new?",
    "What's the best thing to do on a sunny day?",
    "What's the most common thing people keep in a backpack?",
    "What's the most normal thing to do while listening to music?",
    "What's the best thing to do when you're waiting for someone?",
    "What's the most common thing people decorate their room with?",
    "What's the most normal thing to do after watching a movie?",
    "What's the best thing to do on a day with no plans?",
    "What's the most common thing people use a calendar for?",
    "What's the most normal thing to do when you get a new pair of shoes?",
    "What's the best thing to do at a park?",
    "What's the most common thing people collect?",
    "What's the most normal thing to do when something breaks?",
    "What's the best thing to do during a long car ride?",
    "What's the most common thing people put on their walls?",
    "What's the most normal thing to do when someone visits your house?",
    "What's the best thing to do on a quiet evening?",
    "What's the most common thing people carry in their pockets?",
    "What's the most normal thing to do before leaving the house?",
    "What's the best thing to do when the weather is bad?",
    "What's the most common thing people use a camera for?",
    "What's the most normal thing to do when you hear your favourite song?",
    "What's the best thing to do with friends after school or work?",
    "What's the most common thing people put on their desk?",
    "What's the most normal thing to do when you receive a package?",
    "What's the best thing to do during a long weekend?",
    "What's the most common thing people do when they get home?",
    "What's the most normal thing to do when you have visitors?",
    "What's the best thing to do outside on a warm day?",
    "What's the most common thing people use headphones for?",
    "What's the most normal thing to do when you finish a big task?",
    "What's the best thing to do when you wake up earlier than expected?",
    "What's the most common thing people put on a keychain?",
    "What's the most normal thing to do when you get a day off?",
    "What's the best thing to do when you have nothing planned?",
    "What's the most common thing people keep beside their bed?",
    "What's the most normal thing to do while waiting in a queue?",
    "What's the best thing to do when you want to relax?",
    "What's the most common thing people do before going to sleep?",
    "What's the most normal thing to do when plans change?",
    "What's the best thing to do when you find a new favourite song?",
    "What's the most common thing people do when they're excited?",
    "What's the most normal way to spend a completely free day?"
];
