export const ridiculousQuestions = [
    "What's the worst name for a pet?",
    "What's the most useless superpower?",
    "What's the funniest thing to put on a sandwich?",
    "What's the worst thing to hear from your neighbour?",
    "Which household object would be hardest to fight?",
    "What's the least intimidating animal?",
    "What's the worst name for a restaurant?",
    "What's the funniest thing to find in your backpack?",
    "What's the worst thing to shout in a supermarket?",
    "What's the strangest thing to bring to a picnic?",
    "What's the worst possible name for a school?",
    "What's the least useful thing to bring on a camping trip?",
    "What's the funniest thing to put on a birthday cake?",
    "What's the worst thing for a robot to say?",
    "What's the strangest thing to wear to a fancy dinner?",
    "What's the worst thing to discover in your fridge?",
    "What's the funniest thing for a dog to be afraid of?",
    "What's the worst thing to name a boat?",
    "What's the least useful invention?",
    "What's the funniest thing to find under your bed?",
    "What's the worst thing to accidentally say during a presentation?",
    "What's the strangest thing to put in a lunchbox?",
    "What's the worst name for a superhero?",
    "What's the funniest thing a cat could be the boss of?",
    "What's the worst thing to bring to a swimming pool?",
    "What's the least useful thing to have in your backpack?",
    "What's the funniest thing to put in a vending machine?",
    "What's the worst thing to hear from a talking fridge?",
    "What's the strangest thing to find in a shoe?",
    "What's the worst possible name for a shop?",
    "What's the funniest animal to see driving a car?",
    "What's the least useful thing to make invisible?",
    "What's the worst thing to happen during a picnic?",
    "What's the funniest thing to put on a pizza?",
    "What's the worst name for a football team?",
    "What's the strangest thing to use as an umbrella?",
    "What's the least useful thing to have on a desert island?",
    "What's the funniest thing to put in a trophy?",
    "What's the worst thing for a magician to accidentally make appear?",
    "What's the strangest thing to find in a classroom?",
    "What's the worst thing to hear from a vending machine?",
    "What's the funniest thing to have as a school mascot?",
    "What's the least useful thing to have as a robot assistant?",
    "What's the worst thing to find in your lunch?",
    "What's the funniest thing to see at a bus stop?",
    "What's the strangest thing to put in a suitcase?",
    "What's the worst thing to happen at a birthday party?",
    "What's the funniest thing for a duck to be in charge of?",
    "What's the least useful thing to have a remote control for?",
    "What's the worst possible name for a hotel?"
];
