export const schoolQuestions = [
    "What's the most common thing to forget at school?",
    "What's the best thing to do during lunchtime?",
    "What's the most normal school lunch?",
    "What's the most annoying thing that can happen in class?",
    "What's the most common excuse for forgetting homework?",
    "What's the first thing students do when class ends?",
    "What's the most normal thing to keep in a school bag?",
    "What's the best thing about a free lesson?",
    "What's the most common thing students talk about?",
    "What's the most normal thing to do before school?",
    "What's the most common thing people forget for sport?",
    "What's the best thing to do during a school break?",
    "What's the most normal classroom object?",
    "What's the most common reason someone is late to class?",
    "What's the best thing to do when a lesson finishes early?",
    "What's the most normal thing to buy at a school canteen?",
    "What's the most common thing found in a pencil case?",
    "What's the best school subject to have a free period in?",
    "What's the most normal thing to do on the first day of school?",
    "What's the most common thing students borrow?",
    "What's the best thing about Friday at school?",
    "What's the most normal thing to do after school?",
    "What's the most common thing written in a notebook?",
    "What's the best thing to bring for lunch?",
    "What's the most normal thing to do during a group project?",
    "What's the most common thing students lose?",
    "What's the best thing to do on a school excursion?",
    "What's the most normal thing to find in a locker?",
    "What's the most common thing people ask a teacher?",
    "What's the best thing about school holidays?",
    "What's the most normal thing to do before an exam?",
    "What's the most common thing people forget before an excursion?",
    "What's the best thing to do at recess?",
    "What's the most normal thing to have on a school desk?",
    "What's the most common thing students complain about?",
    "What's the best thing to do when you finish your work early?",
    "What's the most normal school event?",
    "What's the most common thing people bring to school?",
    "What's the best thing about lunchtime?",
    "What's the most normal thing to do when waiting for class?",
    "What's the most common thing students doodle?",
    "What's the best thing to do after a test?",
    "What's the most normal thing to do during a school assembly?",
    "What's the most common thing people forget to charge?",
    "What's the best thing about the last day of term?",
    "What's the most normal thing to do during a rainy lunch break?",
    "What's the most common thing found under a school desk?",
    "What's the best thing to pack for a school day?",
    "What's the most normal thing to do when a teacher is running late?",
    "What's the best thing about being finished with school for the day?"
];
