export const sportQuestions = [
    "What's the most popular sport to watch?",
    "What's the most normal sport to play with friends?",
    "What's the best sport to watch on TV?",
    "What's the most common thing spectators shout?",
    "What's the most normal thing to bring to a sporting event?",
    "What's the worst thing that can happen during a game?",
    "What's the best sport for a sunny day?",
    "What's the most common sports snack?",
    "What's the most normal thing to do after winning?",
    "What's the most common reason someone misses training?",
    "What's the best sport to play at school?",
    "What's the most annoying thing an opponent can do?",
    "What's the most normal sports uniform?",
    "What's the best sport to play with friends?",
    "What's the most common thing people do when their team scores?",
    "What's the most normal thing to do before a game?",
    "What's the best sport to watch with friends?",
    "What's the most common sporting injury?",
    "What's the most normal thing to bring to training?",
    "What's the best sport for a rainy day?",
    "What's the most common thing coaches say?",
    "What's the most normal thing to do after training?",
    "What's the best sport for a group of friends?",
    "What's the most common thing people forget at training?",
    "What's the most normal thing to do when your team loses?",
    "What's the best sporting event to attend?",
    "What's the most common sports drink?",
    "What's the most normal thing to do during half-time?",
    "What's the best sport to play at the park?",
    "What's the most common thing people wear to watch sport?",
    "What's the most normal way to celebrate a win?",
    "What's the best sport to learn as a beginner?",
    "What's the most common thing people say after missing a shot?",
    "What's the most normal thing to do before a big game?",
    "What's the best sport to play at the beach?",
    "What's the most common thing found in a sports bag?",
    "What's the most normal thing to do when you're waiting for a game?",
    "What's the best sport to play indoors?",
    "What's the most common reason people join a sports team?",
    "What's the most normal thing to do after scoring?",
    "What's the best sport to play in a backyard?",
    "What's the most common thing spectators bring to a game?",
    "What's the most normal sports celebration?",
    "What's the best sport to play with no equipment?",
    "What's the most common thing people do before watching a big game?",
    "What's the most normal thing to hear from a referee?",
    "What's the best sport to play with a ball?",
    "What's the most common thing people do after a close game?",
    "What's the most normal thing to do when your team is winning?",
    "What's the best thing about playing sport?"
];
