export const travelQuestions = [
    "What's the first thing you do when you arrive at a hotel?",
    "What's the most normal thing to pack for a trip?",
    "What's the best seat on a plane?",
    "What's the most common thing people forget when travelling?",
    "What's the most normal airport food?",
    "What's the first thing you do when you reach your destination?",
    "What's the most annoying thing about travelling?",
    "What's the most normal souvenir to buy?",
    "What's the most common reason someone misses a flight?",
    "What's the most normal thing to do on a road trip?",
    "What's the best thing to do on a long flight?",
    "What's the most common thing people overpack?",
    "What's the most normal holiday activity?",
    "What's the worst thing to discover you've forgotten at home?",
    "What's the most normal thing to photograph on holiday?",
    "What's the best thing to pack in your carry-on?",
    "What's the most common thing people do at an airport?",
    "What's the most normal road-trip snack?",
    "What's the best thing about staying in a hotel?",
    "What's the most common thing people take photos of while travelling?",
    "What's the most normal thing to do on the first day of a holiday?",
    "What's the best seat on a train?",
    "What's the most common thing people forget to charge?",
    "What's the most normal thing to do while waiting at an airport?",
    "What's the best thing to do on a long car trip?",
    "What's the most common thing people buy at an airport?",
    "What's the most normal thing to put in a suitcase?",
    "What's the best thing to do when arriving somewhere new?",
    "What's the most common thing people check before a trip?",
    "What's the most normal thing to do on a beach holiday?",
    "What's the best holiday breakfast?",
    "What's the most common thing people bring home from a trip?",
    "What's the most normal thing to do when you get lost?",
    "What's the best thing about a road trip?",
    "What's the most common thing people forget to pack?",
    "What's the most normal thing to do at a train station?",
    "What's the best thing to do while waiting for transport?",
    "What's the most common thing people bring on a plane?",
    "What's the most normal thing to do after checking into a hotel?",
    "What's the best thing to buy as a souvenir?",
    "What's the most common thing people do on holiday?",
    "What's the most normal thing to wear while travelling?",
    "What's the best thing to do on a rainy holiday?",
    "What's the most common thing people check on a map?",
    "What's the most normal thing to do before leaving a hotel?",
    "What's the best thing about travelling with friends?",
    "What's the most common thing people take too many photos of?",
    "What's the most normal thing to do during a long journey?",
    "What's the best thing to do when you arrive home from a trip?",
    "What's the most common thing people look forward to on holiday?"
];
