export const workQuestions = [
    "What's the first thing people do when they arrive at work?",
    "What's the most annoying thing about work?",
    "What's the best part of finishing work?",
    "What's the most common thing people keep on a desk?",
    "What's the most normal lunch break activity?",
    "What's the most common reason someone is late?",
    "What's the most boring work task?",
    "What's the most normal thing to talk about at work?",
    "What's the best thing to do during a break?",
    "What's the most common workplace drink?",
    "What's the most normal thing to do before starting work?",
    "What's the most common thing people complain about at work?",
    "What's the best thing about having a day off?",
    "What's the most normal thing to keep in a work bag?",
    "What's the most common thing people check during a break?",
    "What's the most normal way to start a workday?",
    "What's the most common thing people forget at work?",
    "What's the best thing to do after work?",
    "What's the most normal workplace snack?",
    "What's the most common reason someone takes a break?",
    "What's the most normal thing to do at lunchtime?",
    "What's the most common thing on a noticeboard?",
    "What's the best way to make a boring task more interesting?",
    "What's the most normal thing to say when someone arrives?",
    "What's the most common thing people bring to work?",
    "What's the most normal thing to do when you're waiting for someone?",
    "What's the most common thing people do before leaving work?",
    "What's the best part of a Friday?",
    "What's the most normal thing to do on a quiet workday?",
    "What's the most common thing people need to remember at work?",
    "What's the most normal thing to find in a workplace kitchen?",
    "What's the most common small-talk topic?",
    "What's the best thing to do on a lunch break?",
    "What's the most normal thing to do when work gets busy?",
    "What's the most common thing people write down?",
    "What's the most normal thing to have on a calendar?",
    "What's the best thing about working with other people?",
    "What's the most common thing people do when they finish a task?",
    "What's the most normal thing to do before a meeting?",
    "What's the most common thing people need at work?",
    "What's the most normal reason to check the time at work?",
    "What's the best thing to hear at the end of the day?",
    "What's the most common thing people say when they're busy?",
    "What's the most normal thing to do when you make a mistake?",
    "What's the most common thing people do while waiting for a meeting?",
    "What's the best thing to do after a long day?",
    "What's the most normal thing to do when work is finished early?",
    "What's the most common thing people organise at work?",
    "What's the most normal thing to bring home from work?",
    "What's the best thing about having a weekend off?"
];
