window.familyPrompts = [
    "What is the most common thing families argue about?",
    "What is the worst thing to hear from your parents?",
    "What is something every family has?",
    "What is the best family activity?",
    "What is the worst family activity?",
    "What is something parents always complain about?",
    "What is something siblings always fight over?",
    "What is the best excuse for not doing a chore?",
    "What is the worst chore?",
    "What is something parents think is expensive?",
    "What is something families always forget?",
    "What is the most awkward family conversation?",
    "What is the best family meal?",
    "What is something siblings secretly do?",
    "What is the worst thing to get caught doing?",
    "What is the best thing about having siblings?",
    "What is the worst thing about having siblings?",
    "What is something parents say constantly?",
    "What is the most embarrassing thing a parent can do?",
    "What is something families disagree about on holidays?",
    "What is the best family tradition?",
    "What is the strangest family tradition?",
    "What is the worst thing to happen at a family dinner?",
    "What is something siblings will never agree on?",
    "What is the best excuse to leave a family event?",
    "What is something parents don't understand?",
    "What is something children don't understand?",
    "What is the most annoying thing a sibling can do?",
    "What is the best thing to steal from the family fridge?",
    "What is something families always have too much of?",
    "What is the worst family photo?",
    "What is something parents always say before leaving?",
    "What is the best family holiday?",
    "What is the worst family holiday?",
    "What is something families argue about in the car?",
    "What is the most awkward thing to explain to a relative?",
    "What is something relatives always ask?",
    "What is the worst question a relative can ask?",
    "What is the best thing about visiting relatives?",
    "What is the worst thing about visiting relatives?",
    "What is something everyone blames on a sibling?",
    "What is the best family game?",
    "What is the worst family game?",
    "What is something parents always tell you to clean?",
    "What is the funniest thing a family could argue about?",
    "What is something siblings borrow without asking?",
    "What is the worst thing to happen during a family road trip?",
    "What is something your family would never agree on?",
    "What is the best family snack?",
    "What makes someone the favourite child?"
];
