window.moneyPrompts = [
    "What is something people waste money on?",
    "What would you buy if you suddenly had $1,000?",
    "What is the worst thing to spend your last $20 on?",
    "What is something that is ridiculously overpriced?",
    "What is the best thing to get for free?",
    "What is something people pretend is worth the money?",
    "What is the most useful thing you could buy for $10?",
    "What would you never pay extra for?",
    "What is something people should stop buying?",
    "What is the first thing you would buy after winning the lottery?",
    "What is the worst way to lose money?",
    "What is something that feels expensive even when it isn't?",
    "What is the best thing to buy second-hand?",
    "What is something you would happily spend $100 on?",
    "What is something you would refuse to spend $100 on?",
    "What is the most annoying thing to pay for?",
    "What is something that should be free?",
    "What is the best thing to find in your pocket?",
    "What is the most suspiciously cheap thing?",
    "What is something people buy just to show off?",
    "What is the worst thing to buy online?",
    "What is the best way to spend $50?",
    "What is something you would sell immediately if you owned it?",
    "What is the most pointless expensive product?",
    "What would you buy for your house if money didn't matter?",
    "What is the best thing to save money for?",
    "What is something that always costs more than expected?",
    "What is the worst thing to forget when shopping?",
    "What is something you would never lend money for?",
    "What is the best excuse for being broke?",
    "What is something people spend money on every day?",
    "What is the most satisfying thing to get a discount on?",
    "What is something you would buy if it cost $1?",
    "What is something that is worth paying more for?",
    "What is the worst financial decision someone could make on holiday?",
    "What would you do with a completely useless $500?",
    "What is the most awkward thing to ask someone to pay you back for?",
    "What is something that makes you feel rich?",
    "What is something that makes you feel poor?",
    "What is the best thing to buy at a supermarket?",
    "What is something you would never buy from a vending machine?",
    "What is the most tempting unnecessary purchase?",
    "What is something that should cost less?",
    "What is the worst thing to accidentally buy twice?",
    "What would you spend $5 on?",
    "What is the best money-saving trick?",
    "What is something people buy and immediately regret?",
    "What would you buy if you had exactly $20 left?",
    "What is the most awkward thing to split a bill for?",
    "What is something that is worth every dollar?"
];
