window.sportPrompts = [
    "What is the best sport to watch?",
    "What is the worst sport to play in the rain?",
    "What is the best sport to play with friends?",
    "What is the hardest sport?",
    "What is the easiest sport?",
    "What is the worst sports injury?",
    "What is the best excuse for missing training?",
    "What is the most annoying thing a teammate can do?",
    "What is the best thing about winning?",
    "What is the worst thing about losing?",
    "What is the best sports snack?",
    "What sport would be terrible without shoes?",
    "What sport would be funniest played backwards?",
    "What is the worst sporting venue?",
    "What is the best sporting venue?",
    "What is the most embarrassing thing to happen during a game?",
    "What is the best thing a coach can say?",
    "What is the worst thing a coach can say?",
    "What is something athletes always complain about?",
    "What is the best sport for someone who hates running?",
    "What is the worst sport for someone who hates running?",
    "What sport has the strangest rules?",
    "What is the most unnecessary piece of sports equipment?",
    "What is the best sports uniform?",
    "What is the worst sports uniform?",
    "What is the best way to celebrate a win?",
    "What is the worst way to celebrate a win?",
    "What is the best sporting tradition?",
    "What sport would be funniest with a ball twice the size?",
    "What sport would be funniest with no rules?",
    "What is the worst time to get injured?",
    "What is the best thing about training?",
    "What is the worst thing about training?",
    "What is the most annoying thing about spectators?",
    "What is the best thing a spectator can do?",
    "What is the worst thing a referee can do?",
    "What is the best thing a referee can do?",
    "What sport would be terrible to play indoors?",
    "What sport would be terrible to play outdoors?",
    "What is the best sports movie?",
    "What is the worst sports movie?",
    "What is the most ridiculous sport?",
    "What sport should be added to the Olympics?",
    "What sport should be removed from the Olympics?",
    "What is the best thing to do after a game?",
    "What is the worst thing to do after a game?",
    "What makes someone a good teammate?",
    "What makes someone a terrible teammate?",
    "What is the best sporting comeback?",
    "What is the most important thing in sport?"
];
