window.everydayLifePrompts = [
    "What is the first thing most people do when they wake up?",
    "What is something everyone forgets to do?",
    "What is the most annoying household chore?",
    "What is something people do when they're bored?",
    "What is the most common excuse for being late?",
    "What is something people do when nobody is watching?",
    "What is the worst thing to realise you've forgotten?",
    "What is something people always lose?",
    "What is the most annoying sound in everyday life?",
    "What is something people do before going to bed?",
    "What is the hardest thing to get out of bed for?",
    "What is something people pretend to understand?",
    "What is the most common thing people complain about?",
    "What is something people check way too often?",
    "What is the best excuse to avoid doing something?",
    "What is something people do while waiting?",
    "What is the most awkward everyday situation?",
    "What is something everyone has in their bedroom?",
    "What is something people always leave until the last minute?",
    "What is the worst thing to step on?",
    "What is something people do when they're nervous?",
    "What is the most annoying thing about mornings?",
    "What is something people keep even though they never use it?",
    "What is something that always takes longer than expected?",
    "What is the first thing you would grab during a fire?",
    "What is something people do when they're trying not to laugh?",
    "What is the most satisfying everyday activity?",
    "What is something people constantly forget?",
    "What is the worst place to fall asleep?",
    "What is something people do when they don't know what to say?",
    "What is the most awkward thing to do in public?",
    "What is something everyone has argued about?",
    "What is the best thing about staying home?",
    "What is the worst thing about leaving the house?",
    "What is something people do when they're home alone?",
    "What is the most annoying thing about phones?",
    "What is something people do when they can't sleep?",
    "What is the best thing to do on a lazy day?",
    "What is something people always say they'll do tomorrow?",
    "What is the most common thing to forget when leaving home?",
    "What is something people do while brushing their teeth?",
    "What is the worst everyday inconvenience?",
    "What is something people do when they're embarrassed?",
    "What is the most common reason someone checks the fridge?",
    "What is something people do when they're pretending to be busy?",
    "What is the best way to waste five minutes?",
    "What is something people do when they're waiting for food?",
    "What is the most annoying thing about shopping?",
    "What is something people always have too much of?",
    "What is the best thing about weekends?"
];
