window.foodPrompts = [
    "What is the best takeaway food?",
    "What food is impossible to eat neatly?",
    "What is the most overrated food?",
    "What food could you eat every day?",
    "What is the worst food to eat on a date?",
    "What is the best late-night snack?",
    "What food smells amazing but tastes disappointing?",
    "What is the worst thing to find in your food?",
    "What food belongs at every party?",
    "What is the best breakfast?",
    "What food is better cold?",
    "What is the most annoying food to cook?",
    "What food would you never share?",
    "What is the best thing to put on toast?",
    "What food is impossible to eat quietly?",
    "What is the worst pizza topping?",
    "What food makes the biggest mess?",
    "What is the best chip flavour?",
    "What food would you take to a deserted island?",
    "What is the most suspicious-looking food?",
    "What is the best fast food?",
    "What food should never be microwaved?",
    "What is the worst thing to eat before sport?",
    "What is the best food at a barbecue?",
    "What food do people pretend to like?",
    "What is the best thing to eat when you're sick?",
    "What food would make the worst ice cream flavour?",
    "What is the most disappointing meal?",
    "What is the best dessert?",
    "What food is impossible to stop eating?",
    "What is the worst food combination?",
    "What food would you ban?",
    "What is the best thing to put in a sandwich?",
    "What food is most likely to get stuck in your teeth?",
    "What is the best supermarket snack?",
    "What is the worst thing to spill on yourself?",
    "What food is worth waiting in line for?",
    "What is the most chaotic food to eat in a car?",
    "What food would be terrible at a fancy restaurant?",
    "What is the best comfort food?",
    "What food makes the best leftovers?",
    "What is the worst thing to eat on a plane?",
    "What food would you eat for breakfast if there were no rules?",
    "What is the best sauce?",
    "What food is better homemade?",
    "What is the most divisive food?",
    "What is the best thing to order at a restaurant?",
    "What food would you never eat for money?",
    "What is the worst thing to put in a lunchbox?",
    "What is the ultimate snack?"
];
