window.ridiculousPrompts = [
    "What would be the worst animal to have as a teacher?",
    "What food would be terrifying if it could talk?",
    "What is the worst thing to fall from the sky?",
    "What animal would make the worst roommate?",
    "What would be the funniest thing to yell in a library?",
    "What object would be terrifying if it suddenly became alive?",
    "What is the worst thing to discover in your backpack?",
    "What animal would be terrible at driving?",
    "What would be the worst thing to replace your hands with?",
    "What is the least intimidating superpower?",
    "What would be the worst thing to become famous for?",
    "What animal would make the worst boss?",
    "What is the worst thing to hear from your fridge?",
    "What would be the worst theme for a restaurant?",
    "What is the strangest thing to bring to school?",
    "What animal would be the worst personal trainer?",
    "What would be the worst thing to find under your bed?",
    "What is the worst thing to shout during a wedding?",
    "What object would make the worst pet?",
    "What would be the worst thing to have as a ringtone?",
    "What animal would make the worst taxi driver?",
    "What is the worst name for a superhero?",
    "What would be the worst thing to rain?",
    "What food would make the worst pillow?",
    "What is the worst thing to put in a swimming pool?",
    "What animal would make the worst dentist?",
    "What would be the worst thing to replace your shoes with?",
    "What is the worst thing to hear from a vending machine?",
    "What would be the worst school subject?",
    "What animal would make the worst librarian?",
    "What is the worst thing to find in your lunchbox?",
    "What would be the worst thing to wear to a formal event?",
    "What animal would make the worst politician?",
    "What is the worst possible alarm clock?",
    "What would be the worst thing to discover in your shower?",
    "What animal would make the worst chef?",
    "What is the worst thing to put on a pizza?",
    "What would be the worst thing to name your child?",
    "What animal would make the worst flight attendant?",
    "What is the worst possible flavour of toothpaste?",
    "What would be the worst thing to teleport into?",
    "What animal would make the worst security guard?",
    "What is the worst possible birthday present?",
    "What would be the worst thing to hear from your GPS?",
    "What animal would make the worst teacher's assistant?",
    "What is the worst possible thing to find in your cereal?",
    "What would be the worst thing to have following you everywhere?",
    "What animal would make the worst barber?",
    "What is the worst possible restaurant name?",
    "What would be the worst thing to become invisible while doing?"
];
