window.travelPrompts = [
    "What is the worst thing to forget on holiday?",
    "What is the best thing about travelling?",
    "What is the worst seat on a plane?",
    "What is the first thing you do at a hotel?",
    "What is the best holiday destination?",
    "What is the worst thing about airports?",
    "What is the most annoying thing a tourist can do?",
    "What is the best thing to pack?",
    "What is something people always overpack?",
    "What is the worst thing to lose while travelling?",
    "What is the best holiday food?",
    "What is the worst travel companion?",
    "What is something you should never do on a plane?",
    "What is the best thing about road trips?",
    "What is the worst thing about road trips?",
    "What is the best souvenir?",
    "What is the most useless thing to pack?",
    "What is the worst hotel room?",
    "What is the best thing to find in a hotel room?",
    "What is the most annoying airport announcement?",
    "What is the best thing to do on a long flight?",
    "What is the worst thing to happen at customs?",
    "What is the best travel snack?",
    "What is the worst travel snack?",
    "What is something tourists always take photos of?",
    "What is the most overrated tourist attraction?",
    "What is the best way to waste time at an airport?",
    "What is the worst thing about jet lag?",
    "What is something you should always check before travelling?",
    "What is the best type of holiday?",
    "What is the worst type of holiday?",
    "What is the best thing about camping?",
    "What is the worst thing about camping?",
    "What is something you would never pack in your suitcase?",
    "What is the best travel companion?",
    "What is the worst thing to hear from a pilot?",
    "What is something people do differently on holiday?",
    "What is the best thing to buy at an airport?",
    "What is the worst airport food?",
    "What is something you would happily travel hours for?",
    "What is the best road trip destination?",
    "What is the worst thing to happen on a road trip?",
    "What is the most awkward thing to do in a hotel?",
    "What is something people always forget when packing?",
    "What is the best thing about coming home?",
    "What is the worst thing about coming home?",
    "What is the best thing to do on the first day of a holiday?",
    "What is the worst thing to do on the first day of a holiday?",
    "What is the strangest thing you've seen while travelling?",
    "What makes a holiday memorable?"
];
