window.workPrompts = [
    "What is the worst job to have?",
    "What is the best excuse for being late to work?",
    "What is something people do instead of working?",
    "What is the most annoying thing a boss can say?",
    "What is the best job for someone who hates people?",
    "What is something you should never say in a job interview?",
    "What is the worst thing to happen during a meeting?",
    "What is the best excuse for calling in sick?",
    "What is something people secretly do at work?",
    "What is the most boring job imaginable?",
    "What is something that makes a workplace awkward?",
    "What is the best job perk?",
    "What is the worst thing about working from home?",
    "What is something people pretend to know at work?",
    "What is the most annoying type of coworker?",
    "What is the best reason to take a day off?",
    "What is something you should never put in a work email?",
    "What is the worst thing to spill at work?",
    "What is the funniest thing that could happen in a meeting?",
    "What is a job that sounds easy but isn't?",
    "What is the worst uniform?",
    "What is the best job for someone who loves food?",
    "What is something people complain about at work?",
    "What is the worst thing about Mondays?",
    "What is something that instantly makes work better?",
    "What is the strangest job you can imagine?",
    "What is the best excuse for not answering an email?",
    "What is something people do when the boss walks in?",
    "What is the worst thing to hear from your manager?",
    "What is the best job to have as a teenager?",
    "What is something that should definitely not be a job?",
    "What is the worst office snack?",
    "What is the most awkward workplace conversation?",
    "What is something people do during lunch breaks?",
    "What is the best thing about finishing work?",
    "What is the worst thing to forget at work?",
    "What is the most unnecessary workplace rule?",
    "What is something that makes someone look busy?",
    "What is the best job for someone who hates mornings?",
    "What is the worst thing to happen on your first day?",
    "What is something people always blame on technology?",
    "What is the best thing to do when work is slow?",
    "What is the worst meeting topic?",
    "What is something you would immediately change about your workplace?",
    "What is the most suspicious thing to do during work hours?",
    "What is the best job for someone who loves talking?",
    "What is the worst thing about working with friends?",
    "What is something that should come with a pay rise?",
    "What is the funniest reason someone could quit?",
    "What is the best thing about having a job?"
];
